import type { Segment } from "@/lib/db/types";

export const SEGMENT_LABELS: Record<Segment, string> = {
  beauty: "Beleza",
  barber: "Barbearia",
  aesthetics: "Estética",
  nails: "Manicure",
  lash_brow: "Cílios e sobrancelhas",
  tattoo: "Tatuagem",
  psychology: "Psicologia",
  psychoanalysis: "Psicanálise",
  physio: "Fisioterapia",
  nutrition: "Nutrição",
  speech_therapy: "Fonoaudiologia",
  occupational_therapy: "Terapia ocupacional",
  psychopedagogy: "Psicopedagogia",
  dentistry: "Odontologia",
  medical: "Consultório médico",
  podiatry: "Podologia",
  chiropractic: "Quiropraxia",
  osteopathy: "Osteopatia",
  acupuncture: "Acupuntura",
  massage_therapy: "Massoterapia",
  integrative_therapy: "Terapias integrativas",
  pilates: "Pilates",
  yoga: "Yoga",
  personal_trainer: "Personal trainer",
  pet_grooming: "Banho e tosa",
  veterinary: "Veterinária",
  tutoring: "Aulas particulares",
  photography: "Fotografia",
  consulting: "Consultoria",
  auto_detailing: "Estética automotiva",
  sports_court: "Quadras esportivas",
  general: "Outro / Geral",
};

export const WEEKDAY_LABELS = [
  "Domingo",
  "Segunda",
  "Terça",
  "Quarta",
  "Quinta",
  "Sexta",
  "Sábado",
] as const;
export const WEEKDAY_SHORT = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"] as const;
